"""Reserved tool names for built-in agent skills."""
from __future__ import annotations

BUILTIN_SKILL_NAMES = frozenset({
    "list_my_projects",
    "search_tickets",
    "get_ticket_details",
    "get_sprint_status",
    "search_knowledge_base",
    "semantic_search_kb",
    "search_project_documents",
    "list_kb_spaces",
    "create_kb_page",
    "create_ticket",
    "update_ticket",
    "transition_ticket_status",
    "get_ticket_transitions",
    "present_choices",
    "request_approval",
    "search_issue_reports",
    "create_issue_report",
    "add_reporter_to_issue_report",
    "create_ticket_from_issue_reports",
    "global_search",
    "get_my_dashboard",
    "list_ticket_comments",
    "add_ticket_comment",
    "watch_ticket",
    "unwatch_ticket",
    "list_conversation_attachments",
    "attach_file_to_ticket",
    "attach_file_to_issue_report",
    "calculator",
    "http_request",
})
