"""template_page_type

Revision ID: 64019e2955a9
Revises: 69ed5f1a5ac8
Create Date: 2026-03-25 03:37:29.519490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64019e2955a9'
down_revision: Union[str, None] = '69ed5f1a5ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_templates', sa.Column('page_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_templates', 'page_type')
    # ### end Alembic commands ###
