"""epics_tickets_comments_labels_activity

Revision ID: 68d02666dabb
Revises: 35e110235e43
Create Date: 2026-03-24 19:18:34.347901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68d02666dabb'
down_revision: Union[str, None] = '35e110235e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('color', sa.String(length=7), server_default='#3B82F6', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.String(length=255), server_default='m', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epics_project_id'), 'epics', ['project_id'], unique=False)
    op.create_table('labels',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), server_default='#6B7280', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_project_id'), 'labels', ['project_id'], unique=False)
    op.create_table('tickets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('epic_id', sa.UUID(), nullable=True),
    sa.Column('sprint_id', sa.UUID(), nullable=True),
    sa.Column('parent_ticket_id', sa.UUID(), nullable=True),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(length=50), server_default='task', nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_status_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('story_points', sa.SmallInteger(), nullable=True),
    sa.Column('original_estimate_seconds', sa.Integer(), nullable=True),
    sa.Column('remaining_estimate_seconds', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('board_rank', sa.String(length=255), server_default='m', nullable=False),
    sa.Column('backlog_rank', sa.String(length=255), server_default='m', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_status_id'], ['workflow_statuses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ticket_number', name='uq_tickets_project_number')
    )
    op.create_index(op.f('ix_tickets_assignee_id'), 'tickets', ['assignee_id'], unique=False)
    op.create_index('ix_tickets_backlog_rank', 'tickets', ['project_id', 'backlog_rank'], unique=False, postgresql_where='is_deleted = false AND sprint_id IS NULL')
    op.create_index('ix_tickets_board_rank', 'tickets', ['project_id', 'workflow_status_id', 'board_rank'], unique=False, postgresql_where='is_deleted = false')
    op.create_index(op.f('ix_tickets_epic_id'), 'tickets', ['epic_id'], unique=False)
    op.create_index(op.f('ix_tickets_parent_ticket_id'), 'tickets', ['parent_ticket_id'], unique=False)
    op.create_index('ix_tickets_project_active', 'tickets', ['project_id'], unique=False, postgresql_where='is_deleted = false')
    op.create_index('ix_tickets_search_vector', 'tickets', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_tickets_sprint_id'), 'tickets', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_tickets_workflow_status_id'), 'tickets', ['workflow_status_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_ticket_id'), 'activity_logs', ['ticket_id'], unique=False)
    op.create_table('comments',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_ticket_id'), 'comments', ['ticket_id'], unique=False)
    op.create_table('ticket_dependencies',
    sa.Column('blocking_ticket_id', sa.UUID(), nullable=False),
    sa.Column('blocked_ticket_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=20), server_default='blocks', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocking_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocking_ticket_id', 'blocked_ticket_id', name='uq_ticket_deps_blocking_blocked')
    )
    op.create_index(op.f('ix_ticket_dependencies_blocked_ticket_id'), 'ticket_dependencies', ['blocked_ticket_id'], unique=False)
    op.create_table('ticket_labels',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_labels')
    op.drop_index(op.f('ix_ticket_dependencies_blocked_ticket_id'), table_name='ticket_dependencies')
    op.drop_table('ticket_dependencies')
    op.drop_index(op.f('ix_comments_ticket_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_activity_logs_ticket_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_tickets_workflow_status_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sprint_id'), table_name='tickets')
    op.drop_index('ix_tickets_search_vector', table_name='tickets', postgresql_using='gin')
    op.drop_index('ix_tickets_project_active', table_name='tickets', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_tickets_parent_ticket_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_epic_id'), table_name='tickets')
    op.drop_index('ix_tickets_board_rank', table_name='tickets', postgresql_where='is_deleted = false')
    op.drop_index('ix_tickets_backlog_rank', table_name='tickets', postgresql_where='is_deleted = false AND sprint_id IS NULL')
    op.drop_index(op.f('ix_tickets_assignee_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_labels_project_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_epics_project_id'), table_name='epics')
    op.drop_table('epics')
    # ### end Alembic commands ###
