"""kb_user_story_tables

Revision ID: 69ed5f1a5ac8
Revises: 6a5d50c3f269
Create Date: 2026-03-25 03:33:12.178481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ed5f1a5ac8'
down_revision: Union[str, None] = '6a5d50c3f269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_story_workflows',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_kb_story_workflows_project')
    )
    op.create_index(op.f('ix_kb_story_workflows_project_id'), 'kb_story_workflows', ['project_id'], unique=False)
    op.create_table('kb_story_workflow_statuses',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['kb_story_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'name', name='uq_kb_story_wf_status_name')
    )
    op.create_index(op.f('ix_kb_story_workflow_statuses_workflow_id'), 'kb_story_workflow_statuses', ['workflow_id'], unique=False)
    op.create_table('kb_page_meta',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=False),
    sa.Column('story_workflow_status_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['kb_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_workflow_status_id'], ['kb_story_workflow_statuses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', name='uq_kb_page_meta_page_id')
    )
    op.create_index(op.f('ix_kb_page_meta_page_id'), 'kb_page_meta', ['page_id'], unique=False)
    op.create_index(op.f('ix_kb_page_meta_project_id'), 'kb_page_meta', ['project_id'], unique=False)
    op.create_table('kb_page_ticket_links',
    sa.Column('page_meta_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_meta_id'], ['kb_page_meta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_meta_id', 'ticket_id', name='uq_kb_page_ticket_link')
    )
    op.create_index(op.f('ix_kb_page_ticket_links_page_meta_id'), 'kb_page_ticket_links', ['page_meta_id'], unique=False)
    op.create_index(op.f('ix_kb_page_ticket_links_ticket_id'), 'kb_page_ticket_links', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_page_ticket_links_ticket_id'), table_name='kb_page_ticket_links')
    op.drop_index(op.f('ix_kb_page_ticket_links_page_meta_id'), table_name='kb_page_ticket_links')
    op.drop_table('kb_page_ticket_links')
    op.drop_index(op.f('ix_kb_page_meta_project_id'), table_name='kb_page_meta')
    op.drop_index(op.f('ix_kb_page_meta_page_id'), table_name='kb_page_meta')
    op.drop_table('kb_page_meta')
    op.drop_index(op.f('ix_kb_story_workflow_statuses_workflow_id'), table_name='kb_story_workflow_statuses')
    op.drop_table('kb_story_workflow_statuses')
    op.drop_index(op.f('ix_kb_story_workflows_project_id'), table_name='kb_story_workflows')
    op.drop_table('kb_story_workflows')
    # ### end Alembic commands ###
