"""boards

Revision ID: 8d51c2e80edf
Revises: d2ece1818ab7
Create Date: 2026-03-24 22:27:05.489392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d51c2e80edf'
down_revision: Union[str, None] = 'd2ece1818ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('board_type', sa.String(length=20), server_default='kanban', nullable=False),
    sa.Column('filter_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("board_type IN ('kanban', 'scrum')", name='ck_boards_board_type'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_boards_project_id', 'boards', ['project_id'], unique=False)
    op.create_table('board_columns',
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('workflow_status_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('wip_limit', sa.Integer(), nullable=True),
    sa.Column('is_collapsed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_status_id'], ['workflow_statuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'position', name='uq_board_columns_board_position'),
    sa.UniqueConstraint('board_id', 'workflow_status_id', name='uq_board_columns_board_status')
    )
    op.create_index(op.f('ix_board_columns_board_id'), 'board_columns', ['board_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_columns_board_id'), table_name='board_columns')
    op.drop_table('board_columns')
    op.drop_index('ix_boards_project_id', table_name='boards')
    op.drop_table('boards')
    # ### end Alembic commands ###
