"""time_logs

Revision ID: c422add4e37f
Revises: 8d51c2e80edf
Create Date: 2026-03-24 22:43:52.236160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c422add4e37f'
down_revision: Union[str, None] = '8d51c2e80edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_logs',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seconds_spent', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), server_default='general', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_logs_project_id', 'time_logs', ['project_id'], unique=False)
    op.create_index('ix_time_logs_ticket_id', 'time_logs', ['ticket_id'], unique=False)
    op.create_index('ix_time_logs_user_id', 'time_logs', ['user_id'], unique=False)
    op.create_index('ix_time_logs_work_date', 'time_logs', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_logs_work_date', table_name='time_logs')
    op.drop_index('ix_time_logs_user_id', table_name='time_logs')
    op.drop_index('ix_time_logs_ticket_id', table_name='time_logs')
    op.drop_index('ix_time_logs_project_id', table_name='time_logs')
    op.drop_table('time_logs')
    # ### end Alembic commands ###
